### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by pgrzesiecki** [dano/aioprocessing#11]
Hi,
When I trying install `aioprocessing` using pip I have the following problem:

```bash
$ pip install aioprocessing
Collecting aioprocessing
  Using cached aioprocessing-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ag1hpyyj/aioprocessing/setup.py", line 7, in <module>
        with open("README.md", 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```
**pip** 9.0.1
**python** 3.5.2

**Comment by tomas-fp** [comment]
Same error here too.

**Comment by dano** [comment]
I think this will be fixed once https://github.com/dano/aioprocessing/pull/10 is merged and I re-push the package to PyPI. Just haven't had the time to do it.

**Comment by pgrzesiecki** [comment]
@dano when do you plan to check and merge request and push changes to PyPI?

**Comment by dano** [comment]
@pgrzesiecki Done. Let me know if you still have issues.

**Comment by pgrzesiecki** [comment]
Works perfectly, thanks.
```bash
$ pip install aioprocessing
Collecting aioprocessing
  Downloading aioprocessing-0.0.3.tar.gz
Installing collected packages: aioprocessing
  Running setup.py install for aioprocessing ... done
Successfully installed aioprocessing-0.0.3
```
