### ISSUE TITLE
I tried to write a producer consumer test, but got AttributeError: coro_join on queue

### ISSUE THREAD

**Issue by eromoe** [dano/aioprocessing#13]
Hello,

I wrote below code to test asyncio with aioprocessing.  What I tend to do is start 4 processes, make all io 
call async. 

```
from __future__ import unicode_literals, print_function, absolute_import

import time
import asyncio
import aioprocessing
import multiprocessing

import motor.motor_asyncio 
from humanfriendly import Timer

from parse_result import parse_article

client = motor.motor_asyncio.AsyncIOMotorClient('mongodb://localhost:27017')
resultdb = client['resultdb']
qq_news_history = resultdb['qq_news_history']
qq_news = client['qq_news']['qq_news']


PROCESSES = 4


async def produce(queue):
    curcor = qq_news_history.find({'result.type':'detail'})[:3]

    async for document in curcor:
        await queue.coro_put(document)


async def consume(queue):
    while True:
        item = await queue.coro_get()

        result = parse_article(item)

        if result:
            await qq_news.insert(result)

        queue.task_done()

async def run():

    queue = aioprocessing.AioQueue()

    p = aioprocessing.AioProcess(target=produce, args=(queue,))
    p.start()

    consumers = []


    for i in range(PROCESSES):
        c = aioprocessing.AioProcess(target=consume, args=(queue,))
        c.start()
        consumers.append(c)

    # pool = aioprocessing.AioPool(PROCESSES)
    # tasks = await pool.coro_apply(consume, (queue,))

    # await produce(queue)
    await p.coro_join()
    
    await queue.coro_join()

    for c in consumers:
        await c.coro_join()




if __name__ == "__main__":
    t = Timer()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
    loop.close()
    print('Total running:', t.elapsed_time)
```

But got error at 
```
er awaited
  self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "process_async_multi.py", line 69, in <module>
    loop.run_until_complete(run())
  File "D:\Anaconda3\envs\py3\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "process_async_multi.py", line 54, in run
    await queue.coro_join()
  File "D:\Anaconda3\envs\py3\lib\site-packages\aioprocessing\executor.py", line 60, in __getattr__
    raise AttributeError(attr)
AttributeError: coro_join
```

comment `await queue.coro_join()` , bypass this.  It is confusing,  Process need join, but Queue  don't ?

Besides, I got warnings 

```
D:\Anaconda3\envs\py3\lib\multiprocessing\process.py:93: RuntimeWarning: coroutine 'consume' was nev
er awaited
  self._target(*self._args, **self._kwargs)
D:\Anaconda3\envs\py3\lib\multiprocessing\process.py:93: RuntimeWarning: coroutine 'consume' was nev
er awaited
  self._target(*self._args, **self._kwargs)
D:\Anaconda3\envs\py3\lib\multiprocessing\process.py:93: RuntimeWarning: coroutine 'consume' was nev
er awaited
  self._target(*self._args, **self._kwargs)
D:\Anaconda3\envs\py3\lib\multiprocessing\process.py:93: RuntimeWarning: coroutine 'produce' was nev
er awaited
  self._target(*self._args, **self._kwargs)
D:\Anaconda3\envs\py3\lib\multiprocessing\process.py:93: RuntimeWarning: coroutine 'consume' was nev
er awaited
  self._target(*self._args, **self._kwargs)
```

------------

And  I don't understand why I can't use     

```
    pool = aioprocessing.AioPool(PROCESSES)
    tasks = await pool.coro_apply(consume, (queue,)
 ```

got error : 

```
D:\Anaconda3\envs\py3\lib\multiprocessing\process.py:93: RuntimeWarning: coroutine 'consume' was never awaited
```

Does it mean `pool.coro_apply` do not accept async function ?

**Comment by dano** [comment]
Your first issue is because `multiprocessing.Queue` doesn't have a `join` method, which means `aioProcessing.AioQueue` doesn't have a `coro_join` method. You need to use `JoinableQueue` instead; it does have a `join` method.

Your second issue is because you're passing a coroutine to the `coro_apply` method. `Pool.apply` (and therefore `AioPool.coro_apply`) doesn't support having a coroutine passed to it as the method to execute in the child process. It only supports taking normal functions. The only difference with `coro_apply` is that it won't block the asyncio event loop while it waits for the function to complete. You actually have this same issue with your usage of  `AioProcess`; it can't take a coroutine as the `target`.

For your example to work the way you intend, you need to make `produce` and `consume` normal functions, and have each of them set up their own `asyncio` event loop, then launch your producing and consuming coroutines internally, and wait for them to complete before returning.

**Comment by eromoe** [comment]
Do you mean  I must run both `produce` and `consume` in one process?  
I'd like producer in one process, consumers in other processes . 
I changed code to 
```

async def produce(queue):
    curcor = qq_news_history.find({'result.type':'detail'})

    async for document in curcor:
        await queue.put(document)


async def consume(queue):
    while True:
        item = await queue.get()

        result = parse_article(item)

        if result:
            await qq_news.insert(result)

        queue.task_done()


async def _consume(queue):
    consumer = asyncio.ensure_future(consume(queue))
    await queue.coro_join()
    consumer.cancel()

def produce_loop(queue):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(produce(queue))
    loop.close()

def consume_loop(queue):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(_consume(queue))
    loop.close()


async def run():

    queue = aioprocessing.AioJoinableQueue()

    p = aioprocessing.AioProcess(target=produce_loop, args=(queue,))
    p.start()

    consumers = []

    for i in range(PROCESSES):
        c = aioprocessing.AioProcess(target=consume_loop, args=(queue,))
        c.start()
        consumers.append(c)

    # pool = aioprocessing.AioPool(PROCESSES)
    # tasks = await pool.coro_apply(consume, (queue,))

    # await produce(queue)
    await p.coro_join()
    
    # await queue.coro_join()

    for c in consumers:
        await c.coro_join()


if __name__ == "__main__":
    t = Timer()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
    loop.close()
    print('Total running:', t.elapsed_time)
```

got error 

```
TypeError: object NoneType can't be used in 'await' expression
  File "E:\Project\allproject_git\pyspider_scripts\news\qq\process_async_multi.py", line 43, in _con
sume
    await queue.join()
TypeError: object NoneType can't be used in 'await' expression
Task exception was never retrieved
future: <Task finished coro=<consume() done, defined at E:\Project\allproject_git\pyspider_scripts\n
ews\qq\process_async_multi.py:26> exception=TypeError("object dict can't be used in 'await' expressi
on",)>
Traceback (most recent call last):
  File "E:\Project\allproject_git\pyspider_scripts\news\qq\process_async_multi.py", line 29, in cons
ume
    item = await queue.get()
TypeError: object dict can't be used in 'await' expression
```

**Comment by dano** [comment]
>Do you mean I must run both produce and consume in one process?
No.

The error you're getting is because you're using `await queue.get()` instead of `await queue.coro_get()`.
